[Length]
LightYears = { Megameters = 9460730472.58 }
Megameters = { Kilometers = 1000 }
Kilometers = { Meters = 1000 }
Meters = { Centermetres = 100, Millimeters = 1000, Inches = 39.3701, Fathom = 1.852 }
Centermeters = { Millimeters = 10 }
Millimeters = { Micrometers = 1000 }
Micrometers = { Nanometers = 1000 }
Nanometers = { Picometers = 1000 }
Picometers = { Femtometers = 1000 }
Miles = { Meters = 1609.34 }
Leagues = { Miles = 3 }
NauticalMiles = { Meters = 1852 }

[Weight]
Kilograms = { Grams = 1000 }

[Temperature]
Celsius = { Kelvin = 100, Fahrenheit = 100 }
