[Length]
Kilometers = { Meters = 1000 }
Meters = { Centermetres = 100, Inches = 39.3701, NauticalMiles = 1852, Fathom = 1.852 }
Miles = { Meters = 1609.34 }
Leagues = { Miles = 3 }

[Weight]
Kilograms = { Grams = 1000 }
