[Length]
Kilometers = ['km','k']
Meters = ['m']
Centermeters = ['cm']
Millimeters = ['mm']
Leagues = ['lea']
Miles = ['mi']
Yards = ['yd']
Feet = ['ft']
Inches = ['in']
Fathoms = ['ftm']
NauticalMiles = ['nmi']

[Weight]
Kilograms = ['kg']
Grams = ['g']
