[Length]
LightYears = ['ly']
Megameters = ['Mm']
Kilometers = ['km','k']
Meters = ['m']
Centermeters = ['cm']
Millimeters = ['mm']
Micrometers = ['Î¼m', 'um']
Nanometers = ['nm']
Picometers = ['pm']
Femtometers = ['fm']
Leagues = ['lea']
Miles = ['mi']
Yards = ['yd']
Feet = ['ft']
Inches = ['in']
Fathoms = ['ftm']
NauticalMiles = ['nmi']

[Weight]
Tonnes = ['t']
Kilograms = ['kg']
Grams = ['g']
Centigrams = ['cg']
Milligrams = ['mg']

[Capacity]
Kiloliters = ['kl']
Liters = ['l']
Centiliters = ['cl']
Millimeters = ['ml']

[Temperature]
Celsius = ['C']
Kelvin = ['K']
Fahrenheit = ['F']
